name: Docs

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # ADJUST THIS: we might enable this at a future time.
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ADJUST THIS: install all dependencies (including pdoc)
      # install poetry
      - run: sudo apt install curl
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv pip install .[transformers,kenlm,petals]
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: uv run pdoc -o docs/ surprisal

      - name: Download artifact from pylint
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pylint.yml
          workflow_conclusion: success
          if_no_artifact_found: warn

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
